### ISSUE TITLE
distribute precompiled via npm

### ISSUE THREAD

**Issue by VinSpee** [andrewhathaway/Winterfell#3]
Hi!

I really like where you're headed with this. To make adoption easy, you should set up a `version` task in the `package.json` that precompiles this package so it can be used without having the same build pipeline. See https://github.com/rackt/redux/blob/master/package.json for an example on how to do this well.

Keep up the good work!

**Comment by keisans** [comment]
:+1:

**Comment by andrewhathaway** [comment]
Hi @VinSpee and @keisans!

Great idea. I previously had a dist folder, but didn't commit it due to the fact that the built version included the React library, which isn't ideal as you'll have your own version of React installed.

Whats the usual way to get around this? Or is that acceptable?

Thanks.

**Comment by VinSpee** [comment]
@andrewhathaway I usually stand on the shoulders of giants in this case, and @react-redux does it like this:

- declare react as a `devDependency` in [package.json] (https://github.com/ide/react-redux/commit/b8833e9d31c99b19215477f7116b622a02c31adc)
- have a build step that runs [before you publish to npm](https://github.com/rackt/react-redux/blob/master/package.json#L13)

This allows the consumer to use whichever version of react that they have, avoiding the double-dependency and any peerDep issues. Thanks!
