### ISSUE TITLE
Password confirmation not working

### ISSUE THREAD

**Issue by ryoia** [andrewhathaway/Winterfell#34]
Hi, we are trying to add the password confirmation to the schema, but it doesn't seem like the two password fields talk to each other. We currently have it like following:

"validations" : [{
          "type" : "isEmail"
        }]
      },{
        "questionId" : "password",
        "question" : "Password",
        "input" : {
          "type" : "passwordInput",
          "placeholder" : "8 characters minimum",
          "required" : true
        },
// Make sure password is entered
        "validations" : [{
          "type" : "isLength",
          "params" : [1]
        }]
      },{
        "questionId" : "passwordConfirm",
        "question" : "Password Confirm",
        "input" : {
          "type" : "passwordInput",
          "placeholder" : "confirm password"
        },
        "validations" :[{
          "type" : "equals",
          "params" : ["12345678"]
          //"matches" : "({passwordConfirm}, {password} )"
          //"message" : "Confirm password must match password field"
        }]
Thanks!

**Comment by andrewhathaway** [comment]
Hi there.

This may be due to the Winterfell version you have installed via NPM. If your version is up to date (currently 1.0.4) it most likely does not have this feature yet. However the feature is in the master branch. I will be pushing out a new update sometime soon, meanwhile you could download a copy of the master branch and use that version of Winterfell?

Thanks.

**Comment by andrewhathaway** [comment]
New version published.

**Comment by ryoia** [comment]
This worked, thank you!
