### ISSUE TITLE
Submit button does not submit on all versions of IE

### ISSUE THREAD

**Issue by shobhit-suman** [andrewhathaway/Winterfell#46]
I created a tool based on the form and when I do a submit in IE, I see that it is not submitting. Clicking enter works. It does not log any error to console.

It would be great if you can help in root causing the issue.

**Comment by shobhit-suman** [comment]
@andrewhathaway  I tried running the exampale provided by you, and faced the same issue on it for IE. the submit button doesn't work and it doesnt log any error in the console also
It would be great if you can help in root causing the issue.

**Comment by gantir** [comment]
@andrewhathaway we also noticed that the issue occurs with 0.14 version of react. It works fine with 0.13.3

**Comment by andrewhathaway** [comment]
Hi @shobhit-suman and @gantir.

This is actually an issue with React v0.14.1. If you look in the [changelog here](https://github.com/facebook/react/blob/master/CHANGELOG.md), you'll see that a lot of issues with events not firing in IE due to that issue. That issue has now been fixed in v0.14.2, so please upgrade.

Thanks.
